# Generated by Django 4.2.28 on 2026-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("spotify_id", models.CharField(max_length=255, unique=True, verbose_name="Spotify ID")),
                ("name", models.CharField(max_length=255, verbose_name="titre")),
                ("artists", models.JSONField(default=list, verbose_name="artistes")),
                ("album", models.CharField(max_length=255, verbose_name="album")),
                ("album_image", models.URLField(blank=True, verbose_name="image album")),
                ("duration_ms", models.IntegerField(verbose_name="durée (ms)")),
                ("preview_url", models.URLField(blank=True, null=True, verbose_name="aperçu audio")),
                ("external_url", models.URLField(blank=True, verbose_name="lien Spotify")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="mis à jour le")),
            ],
            options={
                "verbose_name": "morceau",
                "verbose_name_plural": "morceaux",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="playlist",
            options={"ordering": ["-created_at"], "verbose_name": "playlist", "verbose_name_plural": "playlists"},
        ),
        migrations.AddField(
            model_name="playlist",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="lien Spotify"),
        ),
        migrations.AddField(
            model_name="playlist",
            name="owner",
            field=models.CharField(blank=True, max_length=255, verbose_name="propriétaire"),
        ),
    ]
