# Generated by Django 4.2.28 on 2026-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_spotifytoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="spotify_id",
        ),
        migrations.RemoveField(
            model_name="track",
            name="spotify_id",
        ),
        migrations.AddField(
            model_name="playlist",
            name="youtube_id",
            field=models.CharField(default="", max_length=255, unique=True, verbose_name="YouTube ID"),
        ),
        migrations.AddField(
            model_name="track",
            name="youtube_id",
            field=models.CharField(default="", max_length=255, unique=True, verbose_name="YouTube ID"),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="lien YouTube"),
        ),
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.CharField(max_length=255, verbose_name="album/chaîne"),
        ),
        migrations.AlterField(
            model_name="track",
            name="album_image",
            field=models.URLField(blank=True, verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="track",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="lien YouTube"),
        ),
        migrations.AlterField(
            model_name="track",
            name="preview_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL vidéo"),
        ),
        migrations.DeleteModel(
            name="SpotifyToken",
        ),
    ]
