# Generated by Django 5.2.12 on 2026-03-13 19:28

import apps.users.fields
import apps.users.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('email', apps.users.fields.EncryptedEmailField(verbose_name='email address')),
                ('email_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='email hash')),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil (max 5 Mo, JPEG/PNG/WebP/GIF)', null=True, upload_to='avatars/', validators=[apps.users.validators.validate_avatar], verbose_name='avatar')),
                ('total_games_played', models.IntegerField(default=0, verbose_name='parties jouées')),
                ('total_wins', models.IntegerField(default=0, verbose_name='victoires')),
                ('total_points', models.IntegerField(default=0, verbose_name='points totaux')),
                ('coins_balance', models.IntegerField(default=0, help_text='Pièces accumulées via les achievements, utilisables dans la boutique', verbose_name='solde de pièces')),
                ('last_daily_login', models.DateField(blank=True, help_text='Date de la dernière connexion ayant donné le bonus quotidien.', null=True, verbose_name='dernière connexion quotidienne')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, help_text="Date d'acceptation de la politique de confidentialité.", null=True, verbose_name='politique de confidentialité acceptée le')),
                ('cookie_consent_given_at', models.DateTimeField(blank=True, help_text="Date d'acceptation du bandeau de cookies.", null=True, verbose_name='consentement cookies donné le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='avatar')),
                ('total_games', models.IntegerField(default=0, verbose_name='parties jouées')),
                ('total_wins', models.IntegerField(default=0, verbose_name='victoires')),
                ('total_points', models.IntegerField(default=0, verbose_name='points totaux')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'équipe',
                'verbose_name_plural': 'équipes',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('member', 'Membre')], default='member', max_length=20, verbose_name='rôle')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='a rejoint le')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.team', verbose_name='équipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "membre d'équipe",
                'verbose_name_plural': "membres d'équipe",
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='users.TeamMember', to=settings.AUTH_USER_MODEL, verbose_name='membres'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL, verbose_name="de l'utilisateur")),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL, verbose_name="à l'utilisateur")),
            ],
            options={
                'verbose_name': 'amitié',
                'verbose_name_plural': 'amitiés',
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.team', verbose_name='équipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "demande d'adhésion",
                'verbose_name_plural': "demandes d'adhésion",
                'ordering': ['-created_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
