# Generated by Django 4.2.28 on 2026-02-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nom")),
                ("description", models.TextField(blank=True, max_length=500, verbose_name="description")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="team_avatars/", verbose_name="avatar")),
                ("total_games", models.IntegerField(default=0, verbose_name="parties jouées")),
                ("total_wins", models.IntegerField(default=0, verbose_name="victoires")),
                ("total_points", models.IntegerField(default=0, verbose_name="points totaux")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
            ],
            options={
                "verbose_name": "équipe",
                "verbose_name_plural": "équipes",
                "ordering": ["-total_points"],
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Propriétaire"), ("admin", "Administrateur"), ("member", "Membre")],
                        default="member",
                        max_length=20,
                        verbose_name="rôle",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="a rejoint le")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="users.team",
                        verbose_name="équipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "membre d'équipe",
                "verbose_name_plural": "membres d'équipe",
                "ordering": ["joined_at"],
                "unique_together": {("team", "user")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", through="users.TeamMember", to=settings.AUTH_USER_MODEL, verbose_name="membres"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("accepted", "Acceptée"), ("rejected", "Refusée")],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="de l'utilisateur",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="à l'utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "amitié",
                "verbose_name_plural": "amitiés",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
