# Generated by Django 4.2.28 on 2026-02-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_team_remove_user_bio_teammember_team_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamJoinRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("approved", "Approuvée"), ("rejected", "Refusée")],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="users.team",
                        verbose_name="équipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_join_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande d'adhésion",
                "verbose_name_plural": "demandes d'adhésion",
                "ordering": ["-created_at"],
                "unique_together": {("team", "user")},
            },
        ),
    ]
