# Generated by Django 5.1.15 on 2026-03-05 01:01

from django.db import migrations, models

import apps.users.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_privacy_policy_accepted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=apps.users.fields.EncryptedEmailField(verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_hash",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="email hash",
            ),
        ),
    ]
