# Generated by Django 5.1.15 on 2026-03-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_avatar_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='teamjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
