# Generated by Django 5.2.12 on 2026-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_friendship_status_alter_teamjoinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_consent_given_at',
            field=models.DateTimeField(blank=True, help_text="Date d'acceptation du bandeau de cookies.", null=True, verbose_name='consentement cookies donné le'),
        ),
    ]