# Generated by Django 5.2.12 on 2026-03-13 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='icône')),
                ('points', models.IntegerField(default=10, verbose_name='points')),
                ('condition_type', models.CharField(max_length=50, verbose_name='type de condition')),
                ('condition_value', models.IntegerField(verbose_name='valeur de condition')),
                ('condition_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='contexte de condition')),
            ],
            options={
                'verbose_name': 'succès',
                'verbose_name_plural': 'succès',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='débloqué le')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
            ],
            options={
                'verbose_name': 'succès utilisateur',
                'verbose_name_plural': 'succès utilisateurs',
            },
        ),
    ]
