# Generated by Django 5.2.12 on 2026-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_fog_joker_bonus_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebonus',
            name='bonus_type',
            field=models.CharField(choices=[('double_points', 'Points doublés'), ('max_points', 'Points maximum'), ('time_bonus', 'Temps bonus (+15 s)'), ('fifty_fifty', '50/50 (retire 2 mauvaises réponses)'), ('steal', 'Vol de points (-100 pts au 1er)'), ('shield', 'Bouclier (protection vol)'), ('fog', 'Mode brouillard (floute les réponses au prochain round)'), ('joker', 'Joker (réponse fausse comptée comme correcte)')], db_index=True, max_length=30, verbose_name='type de bonus'),
        ),
        migrations.AlterField(
            model_name='gamebonus',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, verbose_name='consommé'),
        ),
        migrations.AlterField(
            model_name='gamebonus',
            name='round_number',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='numéro du round ciblé'),
        ),
    ]