# Generated by Django 5.2.12 on 2026-03-13 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Nom optionnel pour identifier la partie', max_length=100, verbose_name='nom de la partie')),
                ('room_code', models.CharField(help_text='Code unique pour rejoindre la partie', max_length=6, unique=True, verbose_name='code de la salle')),
                ('mode', models.CharField(choices=[('classique', 'Classique'), ('rapide', 'Rapide'), ('generation', 'Génération'), ('paroles', 'Paroles'), ('karaoke', 'Karaoké'), ('mollo', 'Mollo (ralenti)')], db_index=True, default='classique', max_length=20, verbose_name='mode de jeu')),
                ('guess_target', models.CharField(choices=[('artist', 'Artiste'), ('title', 'Titre')], default='title', help_text="En mode QCM Classique/Rapide : deviner l'artiste ou le titre", max_length=10, verbose_name='cible à deviner')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('in_progress', 'En cours'), ('finished', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='waiting', max_length=20, verbose_name='statut')),
                ('max_players', models.IntegerField(default=8, verbose_name='nombre max de joueurs')),
                ('num_rounds', models.IntegerField(default=10, verbose_name='nombre de rounds')),
                ('playlist_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID playlist Deezer')),
                ('is_online', models.BooleanField(default=True, verbose_name='en ligne')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Si activé, la partie apparaît dans la liste des parties publiques', verbose_name='partie publique')),
                ('is_party_mode', models.BooleanField(default=False, help_text="Si activé, l'hôte est spectateur (écran projeté) et les joueurs voient uniquement les boutons de réponse sur leur téléphone.", verbose_name='mode soirée')),
                ('playlist_name', models.CharField(blank=True, default='', help_text='Nom de la playlist sélectionnée (pour affichage)', max_length=255, verbose_name='nom de la playlist')),
                ('playlist_image_url', models.URLField(blank=True, default='', help_text="URL de l'image de la playlist", max_length=500, verbose_name='image de la playlist')),
                ('answer_mode', models.CharField(choices=[('mcq', 'QCM'), ('text', 'Saisie libre')], default='mcq', help_text='QCM ou saisie libre', max_length=10, verbose_name='mode de réponse')),
                ('round_duration', models.IntegerField(default=30, help_text='Durée en secondes de chaque round (10-60)', verbose_name="durée d'un round (secondes)")),
                ('timer_start_round', models.IntegerField(default=5, help_text='Compte à rebours avant le début du round (3-15)', verbose_name='timer début de round (secondes)')),
                ('score_display_duration', models.IntegerField(default=10, help_text="Durée d'affichage du score en fin de round (3-30)", verbose_name='temps affichage score (secondes)')),
                ('lyrics_words_count', models.IntegerField(default=3, help_text='Nombre de mots à deviner dans le mode Paroles (2-10)', verbose_name='nombre de mots à deviner (paroles)')),
                ('bonuses_enabled', models.BooleanField(default=True, help_text='Si désactivé, les joueurs ne peuvent pas utiliser de bonus pendant la partie', verbose_name='bonus activés')),
                ('karaoke_track', models.JSONField(blank=True, default=None, help_text='Champ hérité — préférer karaoke_song. Peuplé automatiquement depuis karaoke_song à la création.', null=True, verbose_name='morceau karaoké (legacy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='démarré le')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='terminé le')),
            ],
            options={
                'verbose_name': 'partie',
                'verbose_name_plural': 'parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255, verbose_name='réponse')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='correct')),
                ('points_earned', models.IntegerField(default=0, verbose_name='points gagnés')),
                ('streak_bonus', models.IntegerField(default=0, verbose_name='bonus série')),
                ('response_time', models.FloatField(verbose_name='temps de réponse (secondes)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='répondu le')),
            ],
            options={
                'verbose_name': 'réponse',
                'verbose_name_plural': 'réponses',
            },
        ),
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expire le')),
            ],
            options={
                'verbose_name': 'invitation de partie',
                'verbose_name_plural': 'invitations de partie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_index=True, default=0, verbose_name='score')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='classement')),
                ('consecutive_correct', models.IntegerField(default=0, help_text='Nombre de bonnes réponses consécutives dans la partie', verbose_name='série en cours')),
                ('is_connected', models.BooleanField(db_index=True, default=True, verbose_name='connecté')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='a rejoint le')),
            ],
            options={
                'verbose_name': 'joueur de partie',
                'verbose_name_plural': 'joueurs de partie',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(verbose_name='numéro du round')),
                ('track_id', models.CharField(max_length=255, verbose_name='ID du morceau')),
                ('track_name', models.CharField(max_length=255, verbose_name='nom du morceau')),
                ('artist_name', models.CharField(max_length=255, verbose_name="nom de l'artiste")),
                ('correct_answer', models.CharField(max_length=255, verbose_name='bonne réponse')),
                ('options', models.JSONField(default=list, verbose_name='options')),
                ('preview_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL preview audio')),
                ('question_type', models.CharField(default='guess_title', max_length=30, verbose_name='type de question')),
                ('question_text', models.CharField(default='Quel est le titre de ce morceau ?', max_length=500, verbose_name='texte de la question')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='données supplémentaires')),
                ('duration', models.IntegerField(default=30, verbose_name='durée (secondes)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='démarré le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
            ],
            options={
                'verbose_name': 'round',
                'verbose_name_plural': 'rounds',
                'ordering': ['game', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='KaraokeSong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('artist', models.CharField(max_length=255, verbose_name='artiste')),
                ('youtube_video_id', models.CharField(help_text='Identifiant de la vidéo YouTube (ex: dQw4w9WgXcQ)', max_length=20, unique=True, verbose_name='ID vidéo YouTube')),
                ('lrclib_id', models.IntegerField(blank=True, help_text='ID numérique sur lrclib.net pour récupérer les paroles synchronisées directement (évite les recherches par nom).', null=True, verbose_name='ID LRCLib')),
                ('album_image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='image album')),
                ('duration_ms', models.IntegerField(default=0, help_text='Durée en millisecondes', verbose_name='durée (ms)')),
                ('is_active', models.BooleanField(default=True, help_text='Seuls les morceaux actifs sont proposés aux joueurs', verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'morceau karaoké',
                'verbose_name_plural': 'morceaux karaoké',
                'ordering': ['artist', 'title'],
            },
        ),
    ]
