# Generated by Django 4.2.28 on 2026-02-15 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "room_code",
                    models.CharField(
                        help_text="Code unique pour rejoindre la partie",
                        max_length=6,
                        unique=True,
                        verbose_name="code de la salle",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("quiz_4", "Quiz 4 réponses"),
                            ("quiz_fastest", "Quiz le plus rapide"),
                            ("karaoke", "Karaoké"),
                        ],
                        default="quiz_4",
                        max_length=20,
                        verbose_name="mode de jeu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "En attente"),
                            ("in_progress", "En cours"),
                            ("finished", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("max_players", models.IntegerField(default=8, verbose_name="nombre max de joueurs")),
                (
                    "playlist_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID playlist Spotify"),
                ),
                ("is_online", models.BooleanField(default=True, verbose_name="en ligne")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="démarré le")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="terminé le")),
            ],
            options={
                "verbose_name": "partie",
                "verbose_name_plural": "parties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.CharField(max_length=255, verbose_name="réponse")),
                ("is_correct", models.BooleanField(default=False, verbose_name="correct")),
                ("points_earned", models.IntegerField(default=0, verbose_name="points gagnés")),
                ("response_time", models.FloatField(verbose_name="temps de réponse (secondes)")),
                ("answered_at", models.DateTimeField(auto_now_add=True, verbose_name="répondu le")),
            ],
            options={
                "verbose_name": "réponse",
                "verbose_name_plural": "réponses",
            },
        ),
        migrations.CreateModel(
            name="GameRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.IntegerField(verbose_name="numéro du round")),
                ("track_id", models.CharField(max_length=255, verbose_name="ID du morceau")),
                ("track_name", models.CharField(max_length=255, verbose_name="nom du morceau")),
                ("artist_name", models.CharField(max_length=255, verbose_name="nom de l'artiste")),
                ("correct_answer", models.CharField(max_length=255, verbose_name="bonne réponse")),
                ("options", models.JSONField(default=list, verbose_name="options")),
                ("duration", models.IntegerField(default=30, verbose_name="durée (secondes)")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="démarré le")),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="terminé le")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="games.game",
                        verbose_name="partie",
                    ),
                ),
            ],
            options={
                "verbose_name": "round",
                "verbose_name_plural": "rounds",
                "ordering": ["game", "round_number"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField(default=0, verbose_name="score")),
                ("rank", models.IntegerField(blank=True, null=True, verbose_name="classement")),
                ("is_connected", models.BooleanField(default=True, verbose_name="connecté")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="a rejoint le")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="games.game",
                        verbose_name="partie",
                    ),
                ),
            ],
            options={
                "verbose_name": "joueur de partie",
                "verbose_name_plural": "joueurs de partie",
                "ordering": ["-score"],
            },
        ),
    ]
