# Generated by Django 4.2.28 on 2026-02-15 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="joueur",
            ),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="games.gameplayer",
                verbose_name="joueur",
            ),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="games.gameround",
                verbose_name="round",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="hôte",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameround",
            unique_together={("game", "round_number")},
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("game", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="gameanswer",
            unique_together={("round", "player")},
        ),
    ]
