# Generated by Django 5.2.12 on 2026-03-13 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL, verbose_name='hôte'),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='games.game', verbose_name='partie'),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_game_invitations', to=settings.AUTH_USER_MODEL, verbose_name='destinataire'),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_game_invitations', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='partie'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL, verbose_name='joueur'),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.gameplayer', verbose_name='joueur'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game', verbose_name='partie'),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.gameround', verbose_name='round'),
        ),
        migrations.AddField(
            model_name='game',
            name='karaoke_song',
            field=models.ForeignKey(blank=True, help_text='Morceau sélectionné depuis le catalogue administré', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.karaokesong', verbose_name='morceau karaoké'),
        ),
        migrations.AlterUniqueTogether(
            name='gameinvitation',
            unique_together={('game', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='gameround',
            unique_together={('game', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='gameanswer',
            unique_together={('round', 'player')},
        ),
    ]
