# Generated by Django 4.2.28 on 2026-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="playlist_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID playlist YouTube"),
        ),
        migrations.AlterField(
            model_name="gameround",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="démarré le"),
        ),
    ]
