# Generated by Django 4.2.28 on 2026-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_change_round_started_at_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Nom optionnel pour identifier la partie",
                max_length=100,
                verbose_name="nom de la partie",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="num_rounds",
            field=models.IntegerField(default=10, verbose_name="nombre de rounds"),
        ),
    ]
