# Generated by Django 4.2.28 on 2026-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_add_game_name_and_num_rounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameround",
            name="preview_url",
            field=models.URLField(blank=True, default="", max_length=500, verbose_name="URL preview audio"),
        ),
    ]
