# Generated by Django 4.2.28 on 2026-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_add_game_modes_and_round_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="mode",
            field=models.CharField(
                choices=[
                    ("quiz_4", "Quiz 4 réponses"),
                    ("blind_test_inverse", "Blind Test Inversé"),
                    ("guess_year", "Année de Sortie"),
                    ("guess_artist", "Trouver l'Artiste"),
                    ("intro", "Intro (3s)"),
                    ("lyrics", "Lyrics"),
                ],
                default="quiz_4",
                max_length=20,
                verbose_name="mode de jeu",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="playlist_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID playlist Deezer"),
        ),
    ]
