# Generated by Django 4.2.28 on 2026-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_mode_alter_game_playlist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="mode",
            field=models.CharField(
                choices=[
                    ("quiz_4", "Quiz 4 réponses"),
                    ("blind_test_inverse", "Trouver le Titre"),
                    ("guess_year", "Année de Sortie"),
                    ("guess_artist", "Trouver l'Artiste"),
                    ("intro", "Intro (3s)"),
                    ("lyrics", "Lyrics"),
                ],
                default="quiz_4",
                max_length=20,
                verbose_name="mode de jeu",
            ),
        ),
    ]
