# Generated by Django 4.2.28 on 2026-02-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_alter_game_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des modes pour les parties multi-modes",
                verbose_name="modes de jeu",
            ),
        ),
    ]
