# Generated by Django 4.2.28 on 2026-02-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_game_modes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des modes pour les parties multi-modes",
                null=True,
                verbose_name="modes de jeu",
            ),
        ),
    ]
