# Generated by Django 4.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_game_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="answer_mode",
            field=models.CharField(
                choices=[("mcq", "QCM (4 réponses)"), ("text", "Saisie libre")],
                default="mcq",
                help_text="QCM (4 réponses) ou saisie libre",
                max_length=10,
                verbose_name="mode de réponse",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="round_duration",
            field=models.IntegerField(
                default=30,
                help_text="Durée en secondes de chaque round (10-60)",
                verbose_name="durée d'un round (secondes)",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="time_between_rounds",
            field=models.IntegerField(
                default=10,
                help_text="Temps de pause entre chaque round (3-30)",
                verbose_name="temps entre les rounds (secondes)",
            ),
        ),
    ]
