# Generated by Django 4.2.28 on 2026-02-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_add_answer_mode_and_timing"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="lyrics_words_count",
            field=models.IntegerField(
                default=1,
                help_text="Nombre de mots à blanker dans le mode Lyrics (1-3)",
                verbose_name="nombre de mots à deviner (lyrics)",
            ),
        ),
    ]
