# Generated by Copilot helper
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_karaoke_song"),
    ]

    operations = [
        migrations.DeleteModel(name="TrackCache"),
    ]
