# Generated by Django 4.2.28 on 2026-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0018_delete_trackcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, la partie apparaît dans la liste des parties publiques",
                verbose_name="partie publique",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="playlist_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL de l'image de la playlist",
                max_length=500,
                verbose_name="image de la playlist",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="playlist_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom de la playlist sélectionnée (pour affichage)",
                max_length=255,
                verbose_name="nom de la playlist",
            ),
        ),
    ]
