# Generated by Django 5.1.15 on 2026-03-05 01:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_gameinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gameinvitation',
            name='unique_pending_invitation_per_recipient',
        ),
        migrations.AlterUniqueTogether(
            name='gameinvitation',
            unique_together={('game', 'recipient')},
        ),
    ]
