# Generated by Django 5.2.12 on 2026-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_game_mode_lent_inverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='correct'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='is_connected',
            field=models.BooleanField(db_index=True, default=True, verbose_name='connecté'),
        ),
    ]