# Generated by Django 5.1.15 on 2026-03-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_gameanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_party_mode',
            field=models.BooleanField(default=False, help_text="Si activé, l'hôte est spectateur (écran projeté) et les joueurs voient uniquement les boutons de réponse sur leur téléphone.", verbose_name='mode soirée'),
        ),
    ]
