# Generated by Django 5.1.15 on 2026-03-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_game_bonuses_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='terminé le'),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='expire le'),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
