# Generated by Django 5.2.12 on 2026-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_alter_game_created_at_alter_game_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='score'),
        ),
    ]