# Generated by Django 5.2.12 on 2026-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_alter_gameplayer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('classique', 'Classique'), ('rapide', 'Rapide'), ('generation', 'Génération'), ('paroles', 'Paroles'), ('karaoke', 'Karaoké'), ('mollo', 'Mollo (ralenti)')], db_index=True, default='classique', max_length=20, verbose_name='mode de jeu'),
        ),
    ]